### ISSUE TITLE
Expose TIMEZONE_OFFSET_MINUTES to default parser

### ISSUE THREAD

**Issue by mjsir911** [derickr/timelib#107]
Hi,

The code for `TIMELIB_FORMAT_TIMEZONE_OFFSET_MINUTES` exists but isn't listed in the `default_format_map` so isn't exposed by default

Is there a reason for this? It is being properly tested, but there's no way to use this through the PHP bindings.

Thanks,

**Comment by derickr** [comment]
It was added to support a feature that MongoDB needed, and there is no specific reason for not including it for PHP. However, the letters in used for the parsing of date/time strings reuses the same letters as that are used for formatting, and PHP also does not have a way to [**format**](https://www.php.net/manual/en/datetime.format.php) a timezone offset in minutes (only in seconds with (`Z`)). Do you have a good reason why you want to use this timezone offset in minutes?
