### ISSUE TITLE
ubsan signed integer overflow

### ISSUE THREAD

**Issue by nikic** [derickr/timelib#108]
Ubsan reports an error for this code:
```
<?php
new DateTime('@21641666666666669708sun');
```
With message:
```
ext/date/lib/tm2unixtime.c:436:39: runtime error: signed integer overflow: 106751991167303 * 86400 cannot be represented in type 'long long'
```
At this line: https://github.com/derickr/timelib/blob/b78a481d22a2887932dd69fd6ec4275f782cf63a/tm2unixtime.c#L436

Not sure what the expected behavior is when it comes to integer overflows in timelib.

**Comment by derickr** [comment]
On 15 April 2021 12:13:24 BST, Nikita Popov ***@***.***> wrote:
>Ubsan reports an error for this code:
>```
><?php
>new ***@***.***');
>```
>With message:
>```
>ext/date/lib/tm2unixtime.c:436:39: runtime error: signed integer
>overflow: 106751991167303 * 86400 cannot be represented in type 'long
>long'
>```
>At this line:
>https://github.com/derickr/timelib/blob/b78a481d22a2887932dd69fd6ec4275f782cf63a/tm2unixtime.c#L436
>
>Not sure what the expected behavior is when it comes to integer
>overflows in timelib.

I'd say "undefined". You give it crazy big numbers, you get unexpected output.

**Comment by derickr** [comment]
I'm going to close this. If you feel really strongly about expecting the right results with broken input, then feel free to reopen it.
