### ISSUE TITLE
Compilation Issue with RHEL 6,7,8 and Amazon Linux

### ISSUE THREAD

**Issue by mdashti** [derickr/timelib#111]
Here are the steps to reproduce the issue on Amazon Linux (but it's pretty similar to do it on RHEL 6, 7 and 8:

Launched an Amazon Linux instance and then:
 - Installed `re2c` Dependency:
```
wget https://codeload.github.com/skvadrik/re2c/tar.gz/refs/tags/0.15.3
tar -xzvf 0.15.3
cd re2c-0.15.3
cd re2c
./autogen.sh
./configure
make
sudo make install
cd ..
cd ..
```
 - Installed `cpputest` Dependency:
```
wget https://github.com/cpputest/cpputest/releases/download/latest-passing-build/cpputest-latest.tar.gz
tar -xzvf cpputest-latest.tar.gz
cd cpputest-latest
autoreconf . -i
./configure
make
sudo make install
cd ..
```
 - Then, tried to build `timelib`:
```
git clone https://github.com/mdashti/timelib
cd timelib
make
```
And, now I get this error:

```
gcc -Wdeclaration-after-statement -O0 -ggdb3 -Wall -Werror -Wextra -fsanitize=undefined -fsanitize=address -Wmaybe-uninitialized -Wmissing-field-initializers -Wshadow -Wno-unused-parameter -pedantic -Wno-implicit-fallthrough -DHAVE_STDINT_H -DHAVE_GETTIMEOFDAY -DHAVE_UNISTD_H -DHAVE_DIRENT_H -I. -o tests/tester-parse-interval tests/tester-parse-interval.c timelib.a -lm -fsanitize=undefined -l:libubsan.so
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_linux_libcdep.o): In function `__sanitizer::GetThreadStackTopAndBottom(bool, unsigned long*, unsigned long*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:106: undefined reference to `pthread_getattr_np'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_linux_libcdep.o): In function `__sanitizer::SetEnv(char const*, char const*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:118: undefined reference to `dlsym'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_linux_libcdep.o): In function `__sanitizer::InitTlsSize()':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:163: undefined reference to `dlsym'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_posix_libcdep.o): In function `__sanitizer::GetNamedMappingFd(char const*, unsigned long)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:310: undefined reference to `shm_open'
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:314: undefined reference to `shm_unlink'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_posix_libcdep.o): In function `__sanitizer::AdjustStackSize(void*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:383: undefined reference to `pthread_attr_setstacksize'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_symbolizer_posix_libcdep.o): In function `__sanitizer::Symbolizer::LateInitialize()':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cc:77: undefined reference to `dlsym'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_linux.o): In function `__asan::AsanDlSymNext(char const*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_linux.cc:188: undefined reference to `dlsym'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o): In function `__asan::AsanTSDInit(void (*)(void*))':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:47: undefined reference to `pthread_key_create'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o): In function `__asan::PlatformTSDDtor(void*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:64: undefined reference to `pthread_setspecific'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o): In function `__asan::AsanTSDGet()':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:52: undefined reference to `pthread_getspecific'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o): In function `__asan::AsanTSDSet(void*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:57: undefined reference to `pthread_setspecific'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(interception_linux.o): In function `__interception::GetRealFunctionAddress(char const*, unsigned long*, unsigned long, unsigned long)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/interception/../../../../src/combined/libsanitizer/interception/interception_linux.cc:29: undefined reference to `dlsym'
/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(interception_linux.o): In function `__interception::GetFuncAddrVer(char const*, char const*)':
/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/interception/../../../../src/combined/libsanitizer/interception/interception_linux.cc:35: undefined reference to `dlvsym'
collect2: error: ld returned 1 exit status
make: *** [tests/tester-parse-interval] Error 1
```

Please note this issue is introduced after `timelib-2018.01` based on our tests at MongoDB.

**Comment by derickr** [comment]
On 22 April 2021 22:10:19 BST, Mohammad Dashti ***@***.***> wrote:
>Here are the steps to reproduce the issue on Amazon Linux (but it's
>pretty similar to do it on RHEL 6, 7 and 8:
>
>Launched an Amazon Linux instance and then:
> - Installed Dependencies:
>    - re2c:
>```
>wget https://codeload.github.com/skvadrik/re2c/tar.gz/refs/tags/0.15.3
>tar -xzvf 0.15.3
>cd re2c-0.15.3
>cd re2c
>./autogen.sh
>./configure
>make
>sudo make install
>cd ..
>```
>    - cpputest
>```
>wget
>https://github.com/cpputest/cpputest/releases/download/latest-passing-build/cpputest-latest.tar.gz
>tar -xzvf cpputest-latest.tar.gz
>cd cpputest-latest
>autoreconf . -i
>./configure
>make
>sudo make install
>cd ..
>```
> - Then, tried to build timelib :
>```
>git clone https://github.com/mdashti/timelib
>cd timelib
>make
>```
>And, now I get this error:
>
>```
>gcc -Wdeclaration-after-statement -O0 -ggdb3 -Wall -Werror -Wextra
>-fsanitize=undefined -fsanitize=address -Wmaybe-uninitialized
>-Wmissing-field-initializers -Wshadow -Wno-unused-parameter -pedantic
>-Wno-implicit-fallthrough -DHAVE_STDINT_H -DHAVE_GETTIMEOFDAY
>-DHAVE_UNISTD_H -DHAVE_DIRENT_H -I. -o tests/tester-parse-interval
>tests/tester-parse-interval.c timelib.a -lm -fsanitize=undefined
>-l:libubsan.so
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_linux_libcdep.o):
>In function `__sanitizer::GetThreadStackTopAndBottom(bool, unsigned
>long*, unsigned long*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:106:
>undefined reference to `pthread_getattr_np'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_linux_libcdep.o):
>In function `__sanitizer::SetEnv(char const*, char const*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:118:
>undefined reference to `dlsym'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_linux_libcdep.o):
>In function `__sanitizer::InitTlsSize()':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:163:
>undefined reference to `dlsym'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_posix_libcdep.o):
>In function `__sanitizer::GetNamedMappingFd(char const*, unsigned
>long)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:310:
>undefined reference to `shm_open'
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:314:
>undefined reference to `shm_unlink'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_posix_libcdep.o):
>In function `__sanitizer::AdjustStackSize(void*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cc:383:
>undefined reference to `pthread_attr_setstacksize'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(sanitizer_symbolizer_posix_libcdep.o):
>In function `__sanitizer::Symbolizer::LateInitialize()':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/sanitizer_common/../../../../src/combined/libsanitizer/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cc:77:
>undefined reference to `dlsym'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_linux.o):
>In function `__asan::AsanDlSymNext(char const*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_linux.cc:188:
>undefined reference to `dlsym'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o):
>In function `__asan::AsanTSDInit(void (*)(void*))':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:47:
>undefined reference to `pthread_key_create'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o):
>In function `__asan::PlatformTSDDtor(void*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:64:
>undefined reference to `pthread_setspecific'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o):
>In function `__asan::AsanTSDGet()':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:52:
>undefined reference to `pthread_getspecific'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(asan_posix.o):
>In function `__asan::AsanTSDSet(void*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/asan/../../../../src/combined/libsanitizer/asan/asan_posix.cc:57:
>undefined reference to `pthread_setspecific'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(interception_linux.o):
>In function `__interception::GetRealFunctionAddress(char const*,
>unsigned long*, unsigned long, unsigned long)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/interception/../../../../src/combined/libsanitizer/interception/interception_linux.cc:29:
>undefined reference to `dlsym'
>/opt/mongodbtoolchain/revisions/a90382f2f4f7be99b003a345b0fc048eef574a82/stow/gcc-v3.9Wv/lib/gcc/x86_64-mongodb-linux/8.3.0/libasan.a(interception_linux.o):
>In function `__interception::GetFuncAddrVer(char const*, char const*)':
>/data/mci/227539e2e07d42127bf6f4be032e6f3b/toolchain-builder/tmp/build-gcc-v3.sh-JXL/build/x86_64-mongodb-linux/libsanitizer/interception/../../../../src/combined/libsanitizer/interception/interception_linux.cc:35:
>undefined reference to `dlvsym'
>collect2: error: ld returned 1 exit status
>make: *** [tests/tester-parse-interval] Error 1
>```
>
>Please note this issue is introduced after `timelib-2018.01` based on
>our tests at MongoDB.

This looks like an issue with your toolchain and the libasan that timelib links in?

I can have a look tomorrow (Friday) but I'm not sure if I can do much about this.

timelib's makefile isn't really portable and removing the libasan and >-fsanitize=undefined -fsanitize=address items from the link line might just do the trick.

**Comment by mdashti** [comment]
Thanks @derickr. I tried different combinations of your suggestions, but none of them works. Would be awesome if you could check and see if you can reproduce it on Amazon Linux (or RHEL 6, 7 or 8).

**Comment by derickr** [comment]
I see that the difference between `timelib-2018.01` and the latest is the following in the Makefile:

```
LDFLAGS=-lm -fsanitize=undefined -l:libubsan.so.1
+LDFLAGS=-lm -fsanitize=undefined -l:libubsan.so
 
 TEST_LDFLAGS=-lCppUTest
 
-CC=gcc-8
+CC=gcc
+CXX=g++
```

I've just tried to reproduce this on a fresh new AWS EC2 instance, and before running the exact commands (except for changing `cd ..` to `cd`) that you illustrated above, I ran: `sudo yum install wget git gcc gcc-c++ autoconf automake libtool`, and afterwards `make test` and there were no errors or linking errors, with the output being:

```
make test
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.......
OK (2457 tests, 2457 ran, 7247 checks, 0 ignored, 0 filtered out, 191 ms)
```

The full log is at https://derickrethans.nl/files/dump/timelib-log.html — and that's all with a freshly minted EC2 t2.micro instance with the default Amazon Linux 2, which has gcc 7.3.

-----

Can you try building it by changing the `CFLAGS` in the `Makefile` to:

```
FLAGS=-O0 -ggdb3 \
    -Wall -Werror -Wextra  \
    -Wmaybe-uninitialized -Wmissing-field-initializers -Wshadow -Wno-unused-parameter \
    -pedantic -Wno-implicit-fallthrough \
    -DHAVE_STDINT_H -DHAVE_GETTIMEOFDAY -DHAVE_UNISTD_H -DHAVE_DIRENT_H -I.# -DDEBUG_PARSER
```

And `LDFLAGS` to:

```
LDFLAGS=-lm
```

This should disable the sanitisers, which I think is what is conflicting with your tool chain.

**Comment by mdashti** [comment]
Thanks @derickr for looking into this.
