### ISSUE TITLE
Unable to Parse  Some TimeZone Files Under `/usr/share/zoneinfo` on Amazon Linux 1, and RHEL 6, 7 and 8

### ISSUE THREAD

**Issue by mdashti** [derickr/timelib#112]
If you cherry pick this commit (https://github.com/mdashti/timelib/commit/711278dc34063e7cb78d76665be021cd0d1aab6d), there's a test that `timelib` fails to compile the timezone file for `Africa/Casablanca` taken from `/usr/share/zoneinfo` of an `Amazon Linux 1` instance. The same issue happens on `RHEL 6`, `7` and `8`.

I had to remove these files/directory in order to be able to run MongoDB on Amazon Linux 1, which depends on `timelib` and fails to start-up if there's a problem with reading timezone files:

```bash
sudo rm -rf /usr/share/zoneinfo/Africa # not all of them were problematic
sudo rm -rf  /usr/share/zoneinfo/America/Godthab
sudo rm -rf  /usr/share/zoneinfo/America/Nuuk
sudo rm -rf  /usr/share/zoneinfo/America/Santiago
sudo rm -rf  /usr/share/zoneinfo/Asia # not all of them were problematic
sudo rm -rf  /usr/share/zoneinfo/Chile # not all of them were problematic
sudo rm -rf  /usr/share/zoneinfo/Iran
sudo rm -rf  /usr/share/zoneinfo/Israel
sudo rm -rf  /usr/share/zoneinfo/Pacific # not all of them were problematic
```

Can you please check what can be the source of this issue?

Please note that it does not happen with the `2018.01` release and everything works fine for the `Amazon Linux 1` instance on that release.

**Comment by mdashti** [comment]
BTW, I've included all timezone files under `/usr/share/zoneinfo` for the `Amazon Linux 1` in the same commit (https://github.com/mdashti/timelib/commit/711278dc34063e7cb78d76665be021cd0d1aab6d) to save you the time to find those. It'd be great if we could make sure that all these files can be parsed correctly.

**Comment by derickr** [comment]
I've had a look, and it seems that the tzid that have the problems are the ones that have an empty POSIX string. This is allowed, and timelib (IMO correctly) warned with that through the `TIMELIB_ERROR_POSIX_MISSING_TTINFO` error code which is what your test output is showing.

I did check whether in these cases, these timezone files, with the empty POSIX string ignored, would produce the right results, and that seems to be the case. I'm therefore making a patch that distinguishes between "corrupt POSIX string", with the original `TIMELIB_ERROR_POSIX_MISSING_TTINFO` (renaming it to `TIMELIB_ERROR_CORRUPT_POSIX_STRING`) **error and return NULL**, and this new situation with an empty POSIX string, for which the `parse_tzinfo` function will return `TIMELIB_ERROR_EMPTY_POSIX_STRING`, but not return NULL.

This way you'd be able to distinguish the two cases. Would that be an acceptable solution?

**Comment by mdashti** [comment]
Thanks @derickr. That seems to be a great solution. As long as the returned value in this case is not null, it'll work.

**Comment by derickr** [comment]
This is now fixed in the repository, and I've also tagged 2021.06.

**Comment by mdashti** [comment]
Thanks @derickr !
