### ISSUE TITLE
How can I disambiguate time of day during an end of DST transition ?

### ISSUE THREAD

**Issue by pawnissimo** [derickr/timelib#115]
I am using timelib to convert a date/time + timezone into a timestamp.
In Eastern Canada ("Canada/Eastern" timezone) DST will end on November 7. At 2am, it will be 1am. How can I configure timelib to differentiate Nov 7, 1:30am before the transition from Nov 7, 1:30am after the transition? Is there a way to indicate this in timelib_time ?

Code snippet:

timelib_time   *t;
timelib_tzinfo *tzi;

t = timelib_time_ctor();
t->y = 2021;
t->m = 11;
t->d = 7;
t->h = 1;
t->i = 30;
t->s = 0;
t->us = 0;
tzi = cached_fetch_tzinfo("Canada/Eastern");
timelib_set_timezone(t, tzi);
timelib_update_ts(t, tzi);
timelib_unixtime2gmt(t, t->sse);
printf("UTC Timestamp (Jan 1st, 1970 Epoch): %lld\n", t->sse);

**Comment by derickr** [comment]
At the moment, timelib can not do this.
