### ISSUE TITLE
Update the Internal Timezone DB to the latest IANA Release

### ISSUE THREAD

**Issue by mdashti** [derickr/timelib#118]
There is a recent 2021b release of the IANA timezone db: https://www.iana.org/time-zones. Can we make sure the internal timezone db stored inside `timelib` is up-to-date with this recent release? If you give me some pointers on how to do it, I can also take care of it and send a PR.

**Comment by derickr** [comment]
There is no need to open tickets for this. I keep track of this myself.

The reason why I haven't updated it yet is that the TZ Coordinator has pushed dubious [changes](https://github.com/eggert/tz/commit/1edbb16e933a6ba6dceefd2bd7057b5ce00dd13c) to the TZ repository that removes certain pre-1970 transitions. Or rather, makes some TZIDs use information from *other* areas as their pre-1970 transitions. This would have made the `Europe/Oslo` (Norway) zone use pre-1970 transitions from Germany (`Europe/Berlin`), for example. Some of these have been reverted, for now. I expect that the TZ Coordinator will want to try to push this again in the future, which will be a massive headache for downstream projects. I don't want to remove that data for PHP users, as it's not backwards compatible, but if I don't then the TZ data that is available through the OS will get out of sync with what PHP and timelib bundle. That's not an ideal situation either, and will impact MongoDB users too if they sometimes use bundled data, and some times OS data.

This is a BC break and I haven't put things through QA yet for PHP to see how much this will break. So you'll have to bear with me for a while to make sure it does not impact a lot.
