### ISSUE TITLE
ISO 8601: decimal values (see PHP bug #53831)

### ISSUE THREAD

**Issue by rentalhost** [derickr/timelib#12]
(_From: php internals, 2017-06-22_)

As mentioned on [PHP doc](http://php.net/manual/en/dateinterval.construct.php) the format is based on [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations), but it doesn't respects, for instance, decimal values (eg. `P2.5D`). [Related bug.](https://bugs.php.net/bug.php?id=53831)

To be discussed: should it allows values like `P.5D`?

**Comment by derickr** [comment]
It probably should. I've marked it as a feature request.

**Comment by rentalhost** [comment]
**There are three things to thinking about too:**

1. If it will works to `TS` (seconds), once that `DateInterval` have not support to milliseconds. Then I guess that it should not be allowed (eg. `T0.5S`).
2. How it will round values. For instance: `T0.11M` is _6.6_ seconds, but it should have an integer value. Or it should be _6_ or _7_. By round rules, it should be _7_.
3. For the top pyramid types, how it will works too. For instance: `T0.01H` not should be converted to minutes (that will be zero), but directly to seconds. `0.01 * 60 (minutes on hour) = 0.6 * 60 (seconds on minutes) = 36`. Then `T0.01H` is equivalent to `T36S`.

**Comment by derickr** [comment]
I am closing this issue. Although it'd be lovely, there are indeed many issues with the interpretation of decimals, and IMO I don't think it's worth the effort to support it here.
