### ISSUE TITLE
timelib_update_ts fails when the timestamp is during a DST-to-normal-time transition

### ISSUE THREAD

**Issue by ComaVN** [derickr/timelib#120]
I encountered this using PHP, and [this PHP bug](https://bugs.php.net/bug.php?id=68549) describes pretty much what happens

I made [a PR for php7.4](https://github.com/php/php-src/pull/7639), but they referred me here, as this is the upstream library PHP uses.

However, it's not clear to me how exactly I can adapt my PR to this project, since there's a difference between the library files in the php project and this project.

**Comment by ComaVN** [comment]
I think I managed to fix it in php without changing timelib, but I still think there's a bug here. I could try to make a PR here if you want?

**Comment by derickr** [comment]
Please provide a failing test case, you can find existing ones in the tests/c directory.

If there is a bug, it needs to be fixed properly and not with a hack in PHP.

**Comment by ComaVN** [comment]
> If there is a bug, it needs to be fixed properly and not with a hack in PHP.

I fully agree :)

**Comment by ComaVN** [comment]
Do you have any feedback on my PR for this?

I also tested it in php's master, and it seems to work fine there too.
