### ISSUE TITLE
Crash in timelib_fetch_timezone_offset if zoneinfo files missing (e.g. PHP-FPM chroot)

### ISSUE THREAD

**Issue by GreenReaper** [derickr/timelib#126]
When moving to a new server I decided to try to move my old Drupal site to PHP 8.1.5 (using deb.sury on Debain Bullseye-backports). After expected fixes for things like curly array braces and error handler definitions, I ended up crashing the php-fpm child in timelib:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555556995e3 in timelib_fetch_timezone_offset (tz=tz@entry=0x0, ts=ts@entry=1650857288, transition_time=transition_time@entry=0x7fffffffba80)
    at ./ext/date/lib/parse_tz.c:1333
1333    ./ext/date/lib/parse_tz.c: No such file or directory.
(gdb) bt
#0  0x00005555556995e3 in timelib_fetch_timezone_offset (tz=tz@entry=0x0, ts=ts@entry=1650857288, transition_time=transition_time@entry=0x7fffffffba80)
    at ./ext/date/lib/parse_tz.c:1333
#1  0x0000555555699764 in timelib_get_time_zone_info (ts=ts@entry=1650857288, tz=tz@entry=0x0) at ./ext/date/lib/parse_tz.c:1423
#2  0x000055555569c32f in timelib_unixtime2local (tm=tm@entry=0x7fffb0fe1b00, ts=1650857288) at ./ext/date/lib/unixtime2tm.c:141
#3  0x000055555567319b in zif_strtotime (execute_data=0x7ffff50154d0, return_value=0x7ffff5015410) at ./ext/date/php_date.c:1059
#4  0x0000555555887edc in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at ./Zend/zend_vm_execute.h:1297
#5  execute_ex (ex=0x0) at ./Zend/zend_vm_execute.h:55404
#6  0x000055555588dcad in zend_execute (op_array=0x7ffff5088000, return_value=0x0) at ./Zend/zend_vm_execute.h:59771
#7  0x00005555558201ed in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at ./Zend/zend.c:1792
#8  0x00005555557bbd01 in php_execute_script (primary_file=primary_file@entry=0x7fffffffe190) at ./main/main.c:2538
#9  0x000055555566aa5d in main (argc=<optimized out>, argv=<optimized out>) at ./sapi/fpm/fpm/fpm_main.c:1914
```
After some poking I realized this was due to PHP-FPM being in chroot mode - it didn't have access to /usr/share/zoneinfo. I was able to resolve this by adding a bind mount, i.e. `mkdir -p /var/www/sitename/usr/share/zoneinfo` and then edit `/etc/fstab`:
```
/usr/share/zoneinfo     /var/www/sitename/usr/share/zoneinfo        none    bind,ro,noatime 0       0
```
...and `mount /var/www/sitename/usr/share/zoneinfo`.

I feel it should have detected that the timezone file (and the whole directory tree) was not there and done something other than crash, perhaps revert to UTC and output a warning. [timelib_fetch_timezone_offset()](https://github.com/derickr/timelib/blob/91c2d9b3c8ea586018af30752353c7f217289f23/parse_tz.c#L790) has no null check on `tz`, nor is it checked when extracted from the passed struct in [timelib_unixtime2local()](https://github.com/derickr/timelib/blob/e447d4a9cdc5ca096319e2d2a218c7a1ea8370da/unixtime2tm.c#L121) or [timelib_get_time_zone_info()](https://github.com/derickr/timelib/blob/91c2d9b3c8ea586018af30752353c7f217289f23/parse_tz.c#L881) - I'm not sure if such checks are timelib's responsibility, or if that of the caller; or omitted for performance reasons. The former appears to be a private function, while the latter two are not.

PHP's date.timezone was set to `Europe/Berlin`, which isn't in [fallbackmap.h](https://github.com/derickr/timelib/blob/master/fallbackmap.h) - but it didn't change if I set it to 'Europe/London' or 'UTC'. While searching for a resolution to this issue I saw warnings about a fallback to UTC being a symptom of chrooting without zoneinfo; maybe it does this if it doesn't outright crash, or did so in the code included within a prior version of PHP.

**Comment by derickr** [comment]
Not a bug in timelib, but in the buggy patches that some Linux distributions use to make PHP use system tzdata. I've added an extra check for these broken implementations in php-src: https://github.com/php/php-src/commit/87f341b1c2841062128290e56991924c6f73a5bd
