### ISSUE TITLE
Support returning month names matching %b and %B format specifiers

### ISSUE THREAD

**Issue by jenniferpeshansky** [derickr/timelib#142]
Add timelib_textual_month_full and timelib_textual_month_3_letter functions that return the appropriate string. There could also be a parameter to control capitalization.

**Comment by derickr** [comment]
Timelib does not have any code currently for formatting `timelib_time` struct according to a set of format specifiers at all.
PHP does this in its own function (https://github.com/php/php-src/blob/master/ext/date/php_date.c#L646), and uses the names in [`mon_full_names` and `mon_short_names`](https://github.com/php/php-src/blob/master/ext/date/php_date.c#L592). MongoDB does it in its own function too (https://github.com/mongodb/mongo/blob/master/src/mongo/db/query/datetime/date_time_support.h#L244). 

I also can't find in your documentation ([`dateFromString`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/dateFromString/#std-label-dateFromString-format-specifiers), [`dateToString`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/dateToString/#std-label-format-specifiers) ) what `%b` and `%B` are supposed to be. PHP uses [`d` and `l`](https://www.php.net/manual/en/datetime.format.php) instead.

The default map in timelib's `default_format_map` does not define `b` and `B` either, and in the tests (`tests/c/parse_date_from_format_test.cpp`) they refer to `TIMELIB_FORMAT_DAY_OF_WEEK_ISO` (`b`) and `TIMELIB_FORMAT_YEAR_ISO` (`B`).

I therefore think it would be best to implement this on the MongoDB side, where you can then also pick the format characters that you'd like, and the exact full/short versions of the month names — perhaps in different cases too.

**Comment by jenniferpeshansky** [comment]
Thank you for responding. We were hoping for timelib functions we could call from the Mongo formatting function (for example [here](https://github.com/mongodb/mongo/blob/dbfc672d325ee924f84c8856f490522c57635acc/src/mongo/db/query/datetime/date_time_support.h#L291), we call dayOfYear which, in turn, calls [timelib_day_of_year](https://github.com/mongodb/mongo/blob/dbfc672d325ee924f84c8856f490522c57635acc/src/mongo/db/query/datetime/date_time_support.cpp#L551).) Specifically, we were hoping for a way to reference the existing [month table](https://github.com/derickr/timelib/blob/22c62589c366d1621f5254d2f33fe185a7f2667b/parse_date.re#L264) in order to have a centralized source of truth.

However, I fundamentally agree that it would be simple enough to create these month tables on the MongoDB side, and that it would be difficult to create something that would fulfill all use cases on the timelib side. 

Thank you for your time!
