### ISSUE TITLE
Timezone DB Version Formatting

### ISSUE THREAD

**Issue by westy92** [derickr/timelib#145]
Why does timelib expose the [underlying TZDB version](https://github.com/derickr/timelib/commit/7105a6e6b4c74449aac4052ec0fab71eef147fcf#diff-bd96a118e4e94c58b36760225cdc3ad829b8c0f3b0dad2b0e8c2a1d7bddb5aceR70002) as `2023.3` instead of `2023c` like [IANA](https://www.iana.org/time-zones) and [ICU](https://github.com/unicode-org/icu/pull/2406/files#diff-28cea60a25289a0424fcf8017759c36fff3df27da3252abcf809322fc48c565bR16)?

**Comment by derickr** [comment]
It comes forth out of PHP's package management, which *requires* semver like version numbers. As prefixes like `c` don't really fit with that, they've been replaced by the number `3` instead.
