### ISSUE TITLE
Inefficient algorithm for converting ts to GMT time in timelib_unixtime2gmt

### ISSUE THREAD

**Issue by derickr** [derickr/timelib#18]
Instead of using a multiplication calculation, it uses an iterative process which is magnitudes slower.

https://github.com/derickr/timelib/blob/master/unixtime2tm.c#L77-L81

For positive TS's, this is handled correctly:

https://github.com/derickr/timelib/blob/master/unixtime2tm.c#L52-L55

**Comment by blar** [comment]
I created a pull request for this issue https://github.com/derickr/timelib/pull/19

**Comment by derickr** [comment]
Fixed through a commit referring to #19.
