### ISSUE TITLE
interval.c date_add does not handle DST forward transition

### ISSUE THREAD

**Issue by KnutHelland** [derickr/timelib#23]
While the `date_sub` handles both DST forward and backward, `date_add` only handles backward... These lines
https://github.com/derickr/timelib/blob/master/interval.c#L162-L166
should be copied to
https://github.com/derickr/timelib/blob/master/interval.c#L128

See also https://bugs.php.net/bug.php?id=75167

**Comment by derickr** [comment]
I think this is fixed now.
