### ISSUE TITLE
Support BIG endian

### ISSUE THREAD

**Issue by omron93** [derickr/timelib#28]
Hi,
does this library support big endian systems?

I am interested mainly in PowerPC64 big endian system. I am seeing error code related to this library in MongoDB which uses this library.

Thank you for information,
M.

**Comment by derickr** [comment]
Sorry, I missed this issue. It should work on PPC64 systems, as PHP uses it successfully on that platform. What error codes do you see with this library on MongoDB? We definitely tested it on that platform too.

**Comment by omron93** [comment]
I've forgotten this issue, sorry. Problem was actually in different part of build system. timelib is working on all platform correctly. Thanks for your response.

So I'm closing this issue.
