### ISSUE TITLE
Missing entries in timezonemap.h

### ISSUE THREAD

**Issue by andrenth** [derickr/timelib#34]
Hi

There are timezones in `timezonedb.h` which are not listed in `timezonemap.h` (e.g. `America/Sao_Paulo`). This causes problems in PHP, such as this one reported in the Symfony framework: https://github.com/symfony/symfony/issues/26550.

**Comment by derickr** [comment]
It is expected that America/Sao_Paulo does not show up in "listAbbreviations", as there is no abbreviation for this timezone:

```
derick@singlemalt:~ $ zdump -v America/Sao_Paulo -c2017,2019
America/Sao_Paulo  -9223372036854775808 = NULL
America/Sao_Paulo  -9223372036854689408 = NULL
America/Sao_Paulo  Sun Feb 19 01:59:59 2017 UT = Sat Feb 18 23:59:59 2017 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 19 02:00:00 2017 UT = Sat Feb 18 23:00:00 2017 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Oct 15 02:59:59 2017 UT = Sat Oct 14 23:59:59 2017 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Oct 15 03:00:00 2017 UT = Sun Oct 15 01:00:00 2017 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 18 01:59:59 2018 UT = Sat Feb 17 23:59:59 2018 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 18 02:00:00 2018 UT = Sat Feb 17 23:00:00 2018 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Nov  4 02:59:59 2018 UT = Sat Nov  3 23:59:59 2018 -03 isdst=0 gmtoff=-10800
America/Sao_Paulo  Sun Nov  4 03:00:00 2018 UT = Sun Nov  4 01:00:00 2018 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  9223372036854689407 = NULL
America/Sao_Paulo  9223372036854775807 = NULL
```

As you can see, it uses -02 and -03.

**Comment by andrenth** [comment]
Thanks. In the past it used to be BRT / BRST. I'm not sure why that changed.

**Comment by derickr** [comment]
Yes, it used to, but not since ``2017a``:

- http://mm.icann.org/pipermail/tz/2016-December/024645.html
- http://mm.icann.org/pipermail/tz-announce/2017-February/000045.html

And yes, Symfony needs to fix this. You can't rely on abbreviations. They are only for *display* output purposes.
