### ISSUE TITLE
Off by one error in do_range_limit_fraction() (PHP bug 75642)

### ISSUE THREAD

**Issue by cmb69** [derickr/timelib#35]
The wrap around behavior of microseconds in [do_range_limit_fraction()](https://github.com/derickr/timelib/blob/6785ae7392b172ed39b9e57d2e8a6cf7a263cc8c/tm2unixtime.c#L36) appears to be broken, since 1000000 µs are allowed. It seems the [respective line](https://github.com/derickr/timelib/blob/6785ae7392b172ed39b9e57d2e8a6cf7a263cc8c/tm2unixtime.c#L42) should be:
````c
	if (*fraction >= 1000000) {
````
See also the [respective PHP bug](https://bugs.php.net/bug.php?id=75642).

**Comment by derickr** [comment]
You're right, that looks broken. Want to make a PR yourself (with test)? Or are you fine with me getting to this when I get to it?

**Comment by cmb69** [comment]
Sorry, I wouldn't know how to write a test for timelib, but a PHPT might look like:
````
--TEST--
Bug #75642 (Wrap around behaviour for microseconds is not working)
--FILE--
<?php
$date = new DateTime('2017-12-31 23:59:59.999999');
var_dump(
    $date->format('Y-m-d H:i:s.u'),
    $date->modify('+1 microsecond')->format('Y-m-d H:i:s.u')
);
?>
===DONE===
--EXPECT--
string(26) "2017-12-31 23:59:59.999999"
string(26) "2018-01-01 00:00:00.000000"
===DONE===
````
