### ISSUE TITLE
Use timelib_malloc() instead of malloc()

### ISSUE THREAD

**Issue by cmb69** [derickr/timelib#41]
Commit c68f45bb6860e671f2d310b44e54656df0679c05 introduced timelib_malloc and friends to allow to override the memory allocators. Apparently, there are still some [direct uses of malloc()](https://github.com/derickr/timelib/search?q=malloc&unscoped_q=malloc), though.

Also it might be useful to document that timelib assumes *infallible* allocators.

**Comment by derickr** [comment]
I have not made this change for `win_dirent.h` as it's not really part of the timelib API, and stands on its own. Thanks for the report!
