### ISSUE TITLE
Usage example 

### ISSUE THREAD

**Issue by ahmad-moussawi** [derickr/timelib#48]
Could you please update the readme file, to write more about it's usage ?

**Comment by westy92** [comment]
I'm also looking for more examples of usage; I haven't been able to find any documentation and I'd really love to use this library!

**Comment by derickr** [comment]
There are some examples in the [tests](https://github.com/derickr/timelib/blob/master/tests/c/issues.cpp), and in the [docs](https://github.com/derickr/timelib/tree/master/docs) directory.

If you let me know what you would like to use this library specifically for, I can add some of these examples to a README file.

**Comment by westy92** [comment]
Thanks, @derickr!

My end goal is twofold; I'm currently using this library indirectly with PHP and I'd like to move my codebase to another language. I'd also like to learn more about the capabilities of the provided functions.

I'd like to build this as a library and then invoke it from another language/platform such as C#, Node.js, Go, etc. I believe wrapping the functions will be pretty straightforward and I'm sure I can find plenty of examples on the internet. I'll only be looking for help on this if I come across some weird behavior.

An example of the sort of documentation I'm looking for at this time is what sort of inputs are supported by  `timelib_strtotime`. To my knowledge, PHP uses this library under the hood, and they have some documentation here: http://php.net/manual/en/datetime.formats.relative.php.

**Comment by derickr** [comment]
@westy92 That's the documentation that I wrote for the timelib library and lists the supported formats, although there are some others as well. They're all linked from http://php.net/manual/en/datetime.formats.php .
