### ISSUE TITLE
Update timezonedb.h to version 2016.2 (2016b)

### ISSUE THREAD

**Issue by mjradwin** [derickr/timelib#5]
Can you make the equivalent `timezonedb.h` change here as you did in the PHP tree (https://github.com/php/php-src/commit/871c5ab09a5147dfe5a524eac4a87a3462da35db) a few days ago?

**Comment by mjradwin** [comment]
Looks like 2016b was just released today. Can we get a new `timezonedb.`?

**Comment by derickr** [comment]
It's up to date now.
