### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Dweller** [derickr/timelib#52]
Hi love the functionality built into PHPs strtotime function.   Am struggling to make it work stand alone.   I’m attempting to parse a string and produce a UNIX UTC bit so far the number as always either 0 or 2038.

And chance of a usage example on how to parse and convert to time_t?

**Comment by derickr** [comment]
Have a look at this test: https://github.com/derickr/timelib/blob/master/tests/c/issues.cpp#L156-L176 — that should give you an example. The 64-bit ``time_t`` value should be in ``t->sse`` (but always as a 64-bit signed integer)

**Comment by derickr** [comment]
Closing this out, as no new comments have been provided in the last 21 days.
