### ISSUE TITLE
Unable to create dates with larger than four digit years

### ISSUE THREAD

**Issue by MisterIcy** [derickr/timelib#63]
Hello there,
As I was browsing php's bugtracker, I stumbled upon this bug [#42351 Unable to create dates with years <= -10000 and >= 10000](https://bugs.php.net/bug.php?id=42351) and I think the problem might be on this line:
https://github.com/derickr/timelib/blob/c3de2a982e28f9b71c29089865e6800fab881dce/parse_date.re#L2147

While PHP's documentation states that the 'Y' format returns a four digit number, in reality it returns the exact number of years of a date. Consider this example:
```php
$dateMax = new \DateTime('@'.PHP_INT_MAX);
echo $dateMax->format('Y'); //Prints 292277026596 - PHP 7.3 running on Debian x64
echo $dateMax->format('y'); //Prints 96

$dateError = DateTime::createFromFormat('Y-m-d', '11111-11-11'); // $dateError is false

$date = new \DateTime('11111-11-11');
echo $date->format('Y-m-d'); //2001-11-11
```

Although there are workarounds (such as feeding the timestamp with mktime, or adding /subtracting a DateInterval to/from a DateTime object), the weird behavior of the constructor should be fixed.

**Comment by timparenti** [comment]
@derickr Would the quoted line need to be fixed in the patch that was offered on #16 or similar? Or is there a subtle difference to the issues I'm missing?

**Comment by derickr** [comment]
@timparenti I think the patch in #16 is mostly there. I now see there is an outstanding question (to me). 

From the original report:

> While PHP's documentation states that the 'Y' format returns a four digit number, in reality it returns the exact number of years of a date.

That's not *quite* true, as it will get pre-padded with 0s up to four characters.

> ```$date = new \DateTime('11111-11-11');```
> ```echo $date->format('Y-m-d'); //2001-11-11```

This really gets parsed as:
```
$ tests/tester-parse-string "11111-11-11"
TS: 0 | 2001-11-11 11:11:00
```

**Comment by derickr** [comment]
The PR (#16) that this ticket refers to has been merged, so I am closing this ticket. It will likely not be in PHP 7.4.
