### ISSUE TITLE
PHP Bug #78669: timezone_abbreviations_list only lists from compiled in db, not PECL timezonedb

### ISSUE THREAD

**Issue by andyj713** [derickr/timelib#68]
In PHP, timezone_abbreviations_list() only lists from compiled in db, not PECL timezonedb. timezone_identifiers_list() works as expected with PECL timezonedb.
Comment to PHP Bug #78669 submission is that it looks like a timelib issue, and as such should be reported upstream (here).

**Comment by derickr** [comment]
timelib's timelib_timezone_abbreviations_list returns a precompiled list of timezone abbreviations for lookups for fallbacks. It is too computationally expensive to do compile this list at each call per process (it takes seconds), and hence the list as returned by the PHP function uses this pre-generated list instead.

I also generally frown upon using abbreviations for any input, as these are often not unique, and/or ambiguous.

If you must have the latest version, then the best course of action is to use the latest PHP version, which will have the latest version of both the timelib library, rules, and this precompiled list.
