### ISSUE TITLE
timelib_parse_from_format() does not set the have_time member

### ISSUE THREAD

**Issue by cmb69** [derickr/timelib#7]
Contrary to `timelib_strtotime()`, `timelib_parse_from_format()` does not properly initialize the `have_time` member of the resulting `timelib_time` struct. Even if a time is given, `have_time` appears to be always `0`.

The supplied test script (PHP, no C, sorry) shows identical results for `date_create()` and `date_create_from_format()` (what is expected); however debugging reveals that `have_time` is `1` for `date_create()`, but `0` for `date_create_from_format()`:

```
<?php

$datestring = '2016-08-07 12:34:56';
var_dump(date_create($datestring));
var_dump(date_create_from_format('Y-m-d H:i:s', $datestring));
```

**Comment by derickr** [comment]
The ``have_*`` struct fields should be considered private flags. PHP shouldn't have exposed them at all.
