### ISSUE TITLE
UBSan violation: signed integer overflow

### ISSUE THREAD

**Issue by nikic** [derickr/timelib#72]
```
<?php
strtotime("10000000000000000 hour");
```

```
/home/nikic/php-src-fuzz/ext/date/lib/tm2unixtime.c:372:31: runtime error: signed integer overflow: 359999991717811200 * 100 cannot be represented in type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/nikic/php-src-fuzz/ext/date/lib/tm2unixtime.c:372:31 in 
```

Probably numbers with that many digits shouldn't be accepted in the first place...

**Comment by nikic** [comment]
Permalink for the referenced line: https://github.com/derickr/timelib/blob/7073479cb0267f34b56e31a9e824e518b2bda3ed/tm2unixtime.c#L372

**Comment by derickr** [comment]
I've merged a "fix". It's not nice, but it does the job. I am not making a new release, as there is nothing critical here.
