### ISSUE TITLE
Bug while parsing timezone in the middle of the string

### ISSUE THREAD

**Issue by smx-smx** [derickr/timelib#73]
The bug happens when parsing a time string that contains a timezone not immediately followed by a space
Already discovered here: https://stackoverflow.com/a/8988859

```php
var_dump(date_create_from_format("D-M-d-H.i.s-T-Y", "Tue-Feb-25-10.21.25-CET-2020"));
var_dump(date_get_last_errors());
```

```
bool(false)
array(4) {
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(2)
  ["errors"]=>
  array(2) {
    [20]=>
    string(47) "The timezone could not be found in the database"
    [28]=>
    string(12) "Data missing"
  }
}
```

```php
var_dump(date_create_from_format("D-M-d-H.i.s-T -Y", "Tue-Feb-25-10.21.25-CET -2020"));
```

```
object(DateTime)#1 (3) {
  ["date"]=>
  string(26) "2020-02-25 10:21:25.000000"
  ["timezone_type"]=>
  int(2)
  ["timezone"]=>
  string(3) "CET"
}
```

**Comment by derickr** [comment]
The problem here is that timezone (abbreviations) can have a `-` in it (`GMT-1200`). The by-format parser consumes as many characters as fit for a specific letter, and in this case, that includes the `-` at the end of `CET-`. This is not possible to change without rewriting the whole parser. As (IMO) this is a rather odd format to begin with, I am closing this as "this is not supported". Thanks for reporting it!

**Comment by smx-smx** [comment]
What about having the parser backtrack if no timezone is found and we have a "-" before ?
Instead of returning an error ("The timezone could not be found in the database") it could backtrack before the previous "-" and repeat the check, so that "CET-2020" would be reduced to just "CET"

**Comment by smx-smx** [comment]
I made an initial patch for this problem.
It's mostly a hack but all tests pass and the string written in the first post is handled
https://github.com/smx-smx/timelib/commit/609a23c17f00fee83f5a3e2005ee621f0e92390e

**Comment by smx-smx** [comment]
I think this issue should be reopened.
Timezone abbreviations have no special character, and should be handled differently from timezones such as `America/Port-au-Prince` (which i agree would be quite awkward and unusual in a time string)
