### ISSUE TITLE
Issue with timelib_get_time_zone_info parsing

### ISSUE THREAD

**Issue by natebrunette** [derickr/timelib#79]
Hi @derickr,

I've resolved most of the issues around modifying dates with relative times, however, in doing so, I ran into a bug I could use some help with.

In `ext/date/lib/tm2unixtime.c` the `do_adjust_timezone` function calls `timelib_get_time_zone_info` passing in the current `sse`. However, if you create a date with a positive timezone offset (I've been testing with Sydney) near a DST jump forward transition, I believe that it's taking the offset from the time in DST (in this case, +11 instead of +10), and when it subtracts it again, it's an hour off. This is problematic if you're trying to move directly to the 2am boundary. It ultimately ends up using the transition before the one that it should and doesn't realize it's in a transition.

**Comment by derickr** [comment]
Could you provide a very specific example, preferably with code?

**Comment by derickr** [comment]
No feedback provided, so closing it out.
