### ISSUE TITLE
UTC vs. Zulu time zone

### ISSUE THREAD

**Issue by gharlan** [derickr/timelib#91]
UTC and the Zulu time zone are not the same.
The Zulu time zone, abbreviated with "Z", is a military time zone with no offset to UTC.

```php
$dt = new DateTime('2020-08-09T12:00Z');
var_dump($dt->getTimeZone()->getName());
```

At the moment the result is "Z": https://3v4l.org/nlHGM
This is correct, if the "Z" in the date-time string is interpreted as a time zone abbreviation.

But following ISO 8601, the "Z" is a designator for UTC (ISO 8601 doesn't handle time zone abbreviations).
https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

So I would expect to get the "UTC" time zone, when passing an ISO 8601 string for UTC date-times.
But maybe it's not worth changing the behavior here. What do you think?

**Comment by derickr** [comment]
I am not quite sure how you infer that "2020-08-09T12:00Z" must be an IOS8601 string? The constructor accepts a wide range of formats.

I am not keen on changing this behaviour, mostly, because it doesn't really serve much of a problem, and it might just break somebody's code.
