### ISSUE TITLE
Signed integer overflow in parse_date.re

### ISSUE THREAD

**Issue by nikic** [derickr/timelib#92]
```
<?php
strtotime("20888888888888888Ms");
```

ubsan complains:

```
parse_date.re:647:57: runtime error: signed integer overflow: 20888888888888888 * 1000 cannot be represented in type 'long long'
```

The relevant code are these multiplications: https://github.com/derickr/timelib/blob/09477f7f6d989eec5d95fa51295b57cc56c3157d/parse_date.re#L650-L656

**Comment by nikic** [comment]
Another very similar one:
```
<?php
strtotime("333333333333333day");
```
Ubsan:
```
/home/nikic/php/php-src-fuzz/ext/date/lib/tm2unixtime.c:372:31: runtime error: signed integer overflow: 287999990849692800 * 100 cannot be represented in type 'long long'
```
Relevant code: https://github.com/derickr/timelib/blob/09477f7f6d989eec5d95fa51295b57cc56c3157d/tm2unixtime.c#L380

**Comment by nikic** [comment]
Oh, it looks like that second issue has already been fixed by https://github.com/derickr/timelib/commit/a548e4abc973eb5a2dd3c894a172aebc3c3f9a6e a while ago. Guess timelib in PHP hasn't been updated since then?

**Comment by derickr** [comment]
I can't reproduce the first error with the latest timelib either (but I can with 2018.01). And I've also just updated timelib in PHP 7.3/7.4 to 2018.04, and in master to 2020.01.

**Comment by nikic** [comment]
Thanks! Running the fuzzer again after the update, the next hit I run into is this one:

```php
<?php
$time=mktime(8,8,8,82222222);
date_sunset($time);
```
with
```
/home/nikic/php/php-src-fuzz/ext/date/lib/astro.c:268:17: runtime error: -nan is outside the range of representable values of type 'long long'
```
which is this line: https://github.com/derickr/timelib/blob/8d5bf201437aa129ea0c686d2c56d11639d06099/astro.c#L268

**Comment by nikic** [comment]
Another:
```php
<?php
new DateTime("@7.");
```
with
```
parse_date.re:1116:8: runtime error: 1.84467e+25 is outside the range of representable values of type 'unsigned long long'
```
which is this line: https://github.com/derickr/timelib/blob/8d5bf201437aa129ea0c686d2c56d11639d06099/parse_date.re#L1116

This one seems a bit distinct from the others though, as the input is not something clearly overflowing here, so might be a "genuine" bug.
