### ISSUE TITLE
timelib_strtotime has arbitrary limit on fraction length

### ISSUE THREAD

**Issue by dstorch** [derickr/timelib#93]
This was discovered by a MongoDB user: see https://jira.mongodb.org/browse/SERVER-49217 for the bug report opened against the MongoDB SERVER code base. MongoDB offers a `$dateFromString` expression, which is implemented using timelib's `timelib_strtotime()` function.

The user's input string was something like this "2006-01-02T15:04:05.123456789Z". Note that this has nanosecond precision, so there are 9 digits after the "." character. However, the code which handles the SOAP format appears to only permit 8 digits of precision. I assume that this was a mistake, and that it should allow for 9 digits rather than 8. In particular, [this line of code|https://github.com/derickr/timelib/blob/8d5bf201437aa129ea0c686d2c56d11639d06099/parse_date.re#L1528] has a hard-coded constant of 9. However, this 9 incorporates the "." character, and therefore only permits 8 numeric digits after the ".". The date string above ("2006-01-02T15:04:05.123456789Z") therefore returns an error when passed to `timelib_strtotime()`. The code appears to work as expected in my testing, parsing the date string to the expected `timelib_time`, if the 9 is changed to a 10 in the aforementioned line of timelib code.

**Comment by derickr** [comment]
I've just had a look, and I can't see why there is a limit at all here. I've just made a [commit](https://github.com/derickr/timelib/commit/12fff7ad830f79688e4ab66671dd2c0a143f6ba2) that removes the arbitrary limit, which also address your issue. It is uncommon for people to have more digits (and timelib only supports microseconds), but there is no reason to limit this.

The fix also solves the problem where timelib would generate an "odd" warning saying that it couldn't find the, as the fallback to a timezone correction is now no longer hit at unexpected points (i.e, a not fully parsed fraction).

It is merged into the `v2018` and master (v2020) branches, and I'll make a release after having looked at a few more reported issues.

**Comment by dstorch** [comment]
Thanks Derick!
