### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by jonnywang** [derickr/timelib#95]
macos 10.15.7

changed
```
error: unknown warning option '-Wmaybe-uninitialized'; did you mean '-Wuninitialized'?
      [-Werror,-Wunknown-warning-option]

-Wuninitialized

ld: library not found for -l:libubsan.so

remove -l:libubsan.so


'long long' is a C++11 extension  

append -std=c++11

ctest: tests/c/all_tests.cpp timelib.a ${C_TESTS}
	$(CXX) -std=c++11 $(CPPFLAGS) $(LDFLAGS) tests/c/all_tests.cpp ${C_TESTS} timelib.a $(TEST_LDFLAGS) -o ctest

```

./date-from-string 8:00 Asia/Shanghai
TS: -3489445440343 | -108607-11-16 08:00:00 LMT Asia/Shanghai
TS: -3489445440343 | -108607-11-15 23:54:17 UTC UTC
Timestamp: -3489445440343000

**Comment by westy92** [comment]
I was having these issues when building on macOS as well.

**Comment by derickr** [comment]
These are all macOS related changes, and make it impossible to build this right on Linux with GCC, which is the developer's platform.

To do this right, the build system needs to be converted to use autoconf, and right now I have no such plans to do that myself.
